name: Pull Request
description: Standard pull request template for changes
title: '[Area] - Short Description'
body:
  - type: textarea
    id: changes
    attributes:
      label: Changes
      description: Explain what changes were made
      placeholder: Explanation of changes goes here
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Any additional notes about this PR
      placeholder: Any other notes go here
    validations:
      required: false

  - type: textarea
    id: test-cases
    attributes:
      label: Test Cases
      description: List test cases and edge cases covered
      placeholder: "- Case A\n- Edge case\n- ..."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If UI changes were made, attach screenshots (normal window + smallest window). If manual testing was done, include HTTP request screenshots or DB before/after. If none apply, remove this section.
      placeholder: Paste screenshots here
    validations:
      required: false

  - type: textarea
    id: todo
    attributes:
      label: To Do
      description: Remaining items that must be done
      placeholder: "- [ ] item 1\n- [ ] ..."
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please go through all items before requesting reviewers
      options:
        - label: 'All commits are tagged with the ticket number'
        - label: 'No linting errors / newline warnings'
        - label: 'All code follows repository-configured formatting'
        - label: 'No merge conflicts'
        - label: 'All checks passing'
        - label: 'Screenshots included for UI changes'
        - label: 'Remove non-applicable sections of this template'
        - label: 'PR assigned to yourself'
        - label: 'Reviewers requested & Slack ping sent'
        - label: "PR linked to the issue (fill in 'Closes #')"
        - label: 'If design-related, notify the designer in Slack'
    validations:
      required: true

  - type: input
    id: closes-issue
    attributes:
      label: Closes
      description: Add the issue number this PR resolves (e.g., Closes #42)
      placeholder: Closes #
    validations:
      required: true
