services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        environment:
            DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
        depends_on:
            - db
            - ws
        volumes:
            - .:/app
            - /app/node_modules
    db:
        image: postgres:17
        container_name: sarge_dev_db
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
    ws:
        container_name: sarge_dev_ws
        build:
            context: ./src/ws/
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        volumes:
            - ./src/ws:/src/ws
            - /src/ws/node_modules
    judge0-api:
        image: judge0/judge0:latest
        ports:
            - '2358:2358'
        environment:
            DATABASE_URL: postgres://judge0:judge0@judge0-db:5432/judge0
            REDIS_HOST: judge0-redis
            REDIS_PORT: 6379
            REDIS_PASSWORD: judge0redis
            AUTHZ_TOKEN: fake-local-token
        depends_on:
            - judge0-db
            - judge0-redis

    judge0-worker:
        image: judge0/judge0:latest
        command: ['./scripts/workers']
        privileged: true
        environment:
            DATABASE_URL: postgres://judge0:judge0@judge0-db:5432/judge0
            REDIS_HOST: judge0-redis
            REDIS_PORT: 6379
            REDIS_PASSWORD: judge0redis
            AUTHZ_TOKEN: fake-local-token
        volumes:
            - judge0-box:/var/local/lib/isolate/0/box
            - judge0-box:/box
        depends_on:
            - judge0-db
            - judge0-redis

    judge0-db:
        image: postgres:15
        environment:
            POSTGRES_USER: judge0
            POSTGRES_PASSWORD: judge0
            POSTGRES_DB: judge0

    judge0-redis:
        image: redis:7
        restart: unless-stopped
        command: redis-server --requirepass judge0redis

volumes:
    postgres_data:
    judge0-box:
