name: Task
description: Create a task that a member can complete.
title: '[Area] - Short Description'
body:
    - type: textarea
      id: description
      attributes:
          label: Description
          description: Provide a brief summary of this issue
      validations:
          required: true

    - type: textarea
      id: acceptance-criteria
      attributes:
          label: Acceptance Criteria
          description: What are the conditions that need to be satisified to complete this task?
      validations:
          required: true

    - type: input
      id: figma-link
      attributes:
          label: Figma Link
          description: Provide the link to the specific design (if applicable)
          placeholder: https://www.figma.com/file/...
      validations:
          required: false

    - type: textarea
      id: mocks
      attributes:
          label: Mocks / Screenshots
          description: Provide mocks, screenshots, or other visuals of this new feature
      validations:
          required: false
