export const candidatesData = [
    {
        id: 'cand_carter_herman_001',
        name: 'Carter Herman',
        email: 'carter.herman@northeastern.edu',
        linkedinUrl: 'https://www.linkedin.com/in/carter-herman/',
        githubUrl: 'https://github.com/carterherman', 
        major: 'Computer Science',
        graduationDate: 'May 2027',
        resumeUrl: null,
        orgId: 'org_nextlab_001',
    },
    {
        id: 'cand_brad_derby_001',
        name: 'Brad Derby',
        email: 'brad.derby@northeastern.edu',
        linkedinUrl: 'https://www.linkedin.com/in/bradfordhderby/',
        githubUrl: 'https://github.com/bradderby',
        major: 'Computer Science',
        graduationDate: 'May 2027',
        resumeUrl: null,
        orgId: 'org_nextlab_001',
    },
    {
        id: 'cand_laith_taher_001',
        name: 'Laith Taher',
        email: 'laith.taher@northeastern.edu',
        linkedinUrl: 'https://www.linkedin.com/in/laith-taher/',
        githubUrl: 'https://github.com/LOTaher',
        major: 'Computer Science',
        graduationDate: 'May 2027',
        resumeUrl: 'https://www.splatte.dev/files/Laith-Taher-Resume.pdf',
        orgId: 'org_nextlab_001',
    },
    {
        id: 'cand_anzhuo_wang_001',
        name: 'Anzhuo Wang',
        email: 'anzhuo.wang@northeastern.edu',
        linkedinUrl: 'https://www.linkedin.com/in/anzhuo-wang/',
        githubUrl: 'https://github.com/anzhuowang',
        major: 'Computer Science',
        graduationDate: 'May 2027',
        resumeUrl: null,
        orgId: 'org_nextlab_001',
    },
    {
        id: 'cand_meggan_shvartsberg_001',
        name: 'Meggan Shvartsberg',
        email: 'meggan.shvartsberg@northeastern.edu',
        linkedinUrl: 'https://www.linkedin.com/in/meggan-shvartsberg/',
        githubUrl: 'https://github.com/megganshvartsberg',
        major: 'Computer Science',
        graduationDate: 'May 2027',
        resumeUrl: null,
        orgId: 'org_nextlab_001',
    },
    {
        id: 'cand_olivia_li_001',
        name: 'Olivia Li',
        email: 'olivia.li@northeastern.edu',
        linkedinUrl: 'https://www.linkedin.com/in/olivia-lii/',
        githubUrl: 'https://github.com/Olivia-li',
        major: 'Computer Science',
        graduationDate: 'May 2027',
        resumeUrl: null,
        orgId: 'org_nextlab_001',
    },
    {
        id: 'cand_bea_luna_001',
        name: 'Bea Luna',
        email: 'bea.luna@northeastern.edu',
        linkedinUrl: null,
        githubUrl: null,
        major: 'Computer Science',
        graduationDate: 'May 2027',
        resumeUrl: null,
        orgId: 'org_nextlab_001',
    },
];
