name: Deploy
on:
    pull_request:
        branches: [main]
jobs:
    format:
        name: Prettier
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v6

            - name: pnpm
              uses: pnpm/action-setup@v6

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 22
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run prettier check
              run: pnpm prettier:check

    lint:
        name: Linting
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v6

            - name: pnpm
              uses: pnpm/action-setup@v6

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 22
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Lint
              run: pnpm lint
