name: Linting Check
on:
    push:
        branches:
            - main
            - develop
    pull_request:
        branches:
            - main
            - develop
            - 'feature/**'
jobs:
    run-linting-check:
        runs-on: ubuntu-latest
        env:
            NEXT_PUBLIC_CDN_BASE: ${{ secrets.NEXT_PUBLIC_CDN_BASE }}
        timeout-minutes: 10
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Setup pnpm
              uses: pnpm/action-setup@v4
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 22
                  cache: 'pnpm'
            - name: Install modules
              run: pnpm install
            - name: Generate Prisma client
              run: pnpm prisma:generate
            - name: Run linting check
              run: pnpm lint
            - name: Build (validation)
              run: pnpm build:check
